.PHONY: start
start:
	@go run ./cmd/main.go

.PHONY: build
build:
	go build -o bin/go-spotify ./cmd/main.go

.PHONY: migrate-up
migrate-up:
	@migrate -path db/migrations -database 'postgres://postgres:postgres@localhost:5432/queue-share?sslmode=disable' up 1

.PHONY: migrate-down
migrate-down:
	@migrate -path db/migrations -database 'postgres://postgres:postgres@localhost:5432/queue-share?sslmode=disable' down 1

.PHONY: migrate-force
migrate-force:
	@migrate -path db/migrations -database 'postgres://postgres:postgres@localhost:5432/queue-share?sslmode=disable' force 1

.PHONY: migrate-version
migrate-version:
	@migrate -path db/migrations -database 'postgres://postgres:postgres@localhost:5432/queue-share?sslmode=disable' version

.PHONY: schema
schema:
	@echo "-- Generated by make schema." > db/schema.sql
	@pg_dump -d queue-share -s >> db/schema.sql
	@sqlc generate

