// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForArtistCacheInsertBulk implements pgx.CopyFromSource.
type iteratorForArtistCacheInsertBulk struct {
	rows                 []ArtistCacheInsertBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForArtistCacheInsertBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForArtistCacheInsertBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].URI,
		r.rows[0].Name,
		r.rows[0].ImageUrl,
		r.rows[0].Genres,
		r.rows[0].Popularity,
		r.rows[0].FollowerCount,
	}, nil
}

func (r iteratorForArtistCacheInsertBulk) Err() error {
	return nil
}

func (q *Queries) ArtistCacheInsertBulk(ctx context.Context, arg []ArtistCacheInsertBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"spotify_artist_cache"}, []string{"id", "uri", "name", "image_url", "genres", "popularity", "follower_count"}, &iteratorForArtistCacheInsertBulk{rows: arg})
}
